custom_movie_api.movies:
  path: '/api/product'
  defaults:
    _controller: '\Drupal\product_api\Controller\ProductController::getProduct'
    _title: 'Product API'
  requirements:
    _role: 'anonymous+authenticated'
